### ISSUE TITLE
Socket error: SSLHandshake failed: -9824

### ISSUE THREAD

**Issue by Sacharkin** [skwerlman/skwerlman.github.io#21] opened 2022-11-23 14:31 UTC
I am not able to connect anymore on a Mac.
Still get this error: `Socket error: SSLHandshake failed: -9824`

**Comment by skwerlman** [comment] 2022-11-25 02:13
what version of macos are you using?

from what i can find, this error seems to mean that the TLS version of the server is too new, which would mean that your install doesnt support TLS 1.3 yet

**Comment by Sacharkin** [comment] 2022-11-25 15:58
I am on the newest version of MacOS (Ventura 13.0.1).
How can I check the current supported TLS version? And how can I allow TLS 1.3?

**Comment by skwerlman** [comment] 2023-01-06 01:28
Can you check if this is working for you now?

I have made 2 relevant config changes; first, TLS 1.2 is now enabled. second, i discovered and fixed a configuration issue which was breaking TLS for several of my other sites, which may have had an effect here

**Comment by Sacharkin** [comment] 2023-01-06 12:12
Still not working, but I think it is a client issue. I also created a ticket for the client.
https://github.com/Cockatrice/Cockatrice/issues/4723

**Comment by ZeldaZach** [comment] 2023-01-08 03:09
@skwerlman Does this appear to be an issue on your servers or with Cockatrice as a whole? I can't easily repro

**Comment by skwerlman** [comment] 2023-01-08 11:26
its hard to know, since i only have one report of it, and cant repro myself

**Comment by grantkovich** [comment] 2023-01-17 03:17
Brand new to the server (though not Cockatrice). Running on MacOS Ventura 13.1 and getting the same error message. I tried [enabling TLS 1.3](https://superuser.com/questions/1217220/how-do-i-enable-tls-1-3-in-ios-and-macos) (not enabled by default on MacOS Ventura) though that didn't solve the problem.

**Comment by skwerlman** [comment] 2023-03-19 20:34
it may be that the issue is what ciphers i have enabled; i support a fairly small list of strong ciphers but [this doc](https://support.apple.com/guide/security/tls-security-sec100a75d12/web) suggests that the ones i support should be fine. does anyone know where i can find an explicit list of ciphers supported by appple by default?

for reference, the cipher selection in my nginx config looks like this:
```
ssl_prefer_server_ciphers on;
ssl_ciphers ECDHE-ECDSA-AES256-GCM-SHA384;
ssl_conf_command Ciphersuites TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384;
ssl_ecdh_curve X25519:secp384r1;
```

**Comment by skwerlman** [comment] 2023-03-19 21:15
Thanks to a friend who happened to run into this and was able to help me test solutions quickly, this is now fixed. the resolution was to stop specifying `ssl_ciphers`, `ssl_conf_command`, and `ssl_ecdh_curve`. Limiting the protocol to TLSv1.3 is enough to limit to only strong modern ciphers

**Closed as completed by skwerlman** 2023-03-19 21:15 UTC
